In [1]:
import pandas as pd
import numpy as np

In [3]:
df1Java = pd.DataFrame({
    'StudentID':[9,11,13,15,17,19,21,23,25,27,29],
    'ScoreJava':[22,66,31,51,71,91,56,32,52,73,92]
})
df1Java

    StudentID  ScoreJava
0           9         22
1          11         66
2          13         31
3          15         51
4          17         71
5          19         91
6          21         56
7          23         32
8          25         52
9          27         73
10         29         92

In [4]:
df2Java = pd.DataFrame({
    'StudentID':[2,4,6,8,10,12,14,16,18,20,22,24,26,28,30],
    'ScoreJava':[98,93,44,77,69,56,31,53,78,93,56,77,33,56,27]
})
df2Java

    StudentID  ScoreJava
0           2         98
1           4         93
2           6         44
3           8         77
4          10         69
5          12         56
6          14         31
7          16         53
8          18         78
9          20         93
10         22         56
11         24         77
12         26         33
13         28         56
14         30         27

In [5]:
df1Python = pd.DataFrame({
    'StudentID':[1,3,5,7,9,11,13,15,17,19,21,23,25,27,29],
    'ScorePython':[39,49,55,77,52,86,41,77,73,51,86,82,92,23,49]
})
df1Python

    StudentID  ScorePython
0           1           39
1           3           49
2           5           55
3           7           77
4           9           52
5          11           86
6          13           41
7          15           77
8          17           73
9          19           51
10         21           86
11         23           82
12         25           92
13         27           23
14         29           49

In [6]:
df2Python = pd.DataFrame({
    'StudentID':[2,4,6,8,10,12,14,16,18,20],
    'ScorePython':[93,44,78,97,87,89,39,43,88,78]
})
df2Python

   StudentID  ScorePython
0          2           93
1          4           44
2          6           78
3          8           97
4         10           87
5         12           89
6         14           39
7         16           43
8         18           88
9         20           78

In [10]:
dfJava = pd.concat([df1Java, df2Java], ignore_index=True)

In [11]:
dfPython = pd.concat([df1Python, df2Python], ignore_index=True)

In [12]:
df = dfJava.merge(dfPython, how='inner')

In [13]:
df

    StudentID  ScoreJava  ScorePython
0           9         22           52
1          11         66           86
2          13         31           41
3          15         51           77
4          17         71           73
5          19         91           51
6          21         56           86
7          23         32           82
8          25         52           92
9          27         73           23
10         29         92           49
11          2         98           93
12          4         93           44
13          6         44           78
14          8         77           97
15         10         69           87
16         12         56           89
17         14         31           39
18         16         53           43
19         18         78           88
20         20         93           78

In [14]:
dfJava = pd.concat([df1Java, df2Java], ignore_index=True)
df

    StudentID  ScoreJava  ScorePython
0           9         22           52
1          11         66           86
2          13         31           41
3          15         51           77
4          17         71           73
5          19         91           51
6          21         56           86
7          23         32           82
8          25         52           92
9          27         73           23
10         29         92           49
11          2         98           93
12          4         93           44
13          6         44           78
14          8         77           97
15         10         69           87
16         12         56           89
17         14         31           39
18         16         53           43
19         18         78           88
20         20         93           78

In [15]:
dfPython = pd.concat([df1Python, df2Python], ignore_index=True)
df

    StudentID  ScoreJava  ScorePython
0           9         22           52
1          11         66           86
2          13         31           41
3          15         51           77
4          17         71           73
5          19         91           51
6          21         56           86
7          23         32           82
8          25         52           92
9          27         73           23
10         29         92           49
11          2         98           93
12          4         93           44
13          6         44           78
14          8         77           97
15         10         69           87
16         12         56           89
17         14         31           39
18         16         53           43
19         18         78           88
20         20         93           78

In [16]:
df = dfJava.merge(dfPython, how='left')
df

    StudentID  ScoreJava  ScorePython
0           9         22         52.0
1          11         66         86.0
2          13         31         41.0
3          15         51         77.0
4          17         71         73.0
5          19         91         51.0
6          21         56         86.0
7          23         32         82.0
8          25         52         92.0
9          27         73         23.0
10         29         92         49.0
11          2         98         93.0
12          4         93         44.0
13          6         44         78.0
14          8         77         97.0
15         10         69         87.0
16         12         56         89.0
17         14         31         39.0
18         16         53         43.0
19         18         78         88.0
20         20         93         78.0
21         22         56          NaN
22         24         77          NaN
23         26         33          NaN
24         28         56          NaN
25         30         27          NaN

In [17]:
dfJava = pd.concat([df1Java, df2Java], ignore_index=True)

In [18]:
dfPython = pd.concat([df1Python, df2Python], ignore_index=True)

In [19]:
df = dfJava.merge(dfPython, how='right')

In [20]:
df

    StudentID  ScoreJava  ScorePython
0           1        NaN           39
1           3        NaN           49
2           5        NaN           55
3           7        NaN           77
4           9       22.0           52
5          11       66.0           86
6          13       31.0           41
7          15       51.0           77
8          17       71.0           73
9          19       91.0           51
10         21       56.0           86
11         23       32.0           82
12         25       52.0           92
13         27       73.0           23
14         29       92.0           49
15          2       98.0           93
16          4       93.0           44
17          6       44.0           78
18          8       77.0           97
19         10       69.0           87
20         12       56.0           89
21         14       31.0           39
22         16       53.0           43
23         18       78.0           88
24         20       93.0           78

In [23]:
data = np.arange(15).reshape((3,5))

In [24]:
indexers = ["Rainfall", "Humidity", "Wind"]

In [25]:
dframe1 = pd.DataFrame(
    data,
    index=indexers,
    columns=["Bergen", "Oslo", "Trondheim", "Stavanger", "Kristiansand"]
)

In [26]:
dframe1

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

In [27]:
stacked = dframe1.stack()

In [28]:
stacked

Rainfall  Bergen           0
          Oslo             1
          Trondheim        2
          Stavanger        3
          Kristiansand     4
Humidity  Bergen           5
          Oslo             6
          Trondheim        7
          Stavanger        8
          Kristiansand     9
Wind      Bergen          10
          Oslo            11
          Trondheim       12
          Stavanger       13
          Kristiansand    14
dtype: int64

In [29]:
stacked.unstack()

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

In [30]:
series1 = pd.Series(
    [0,111,222,333],
    index=["zeros","ones","twos","threes"]
)

In [31]:
series1

zeros       0
ones      111
twos      222
threes    333
dtype: int64

In [32]:
series2 = pd.Series(
    [444,555,666],
    index=["fours","fives","sixs"]
)

In [33]:
series2

fours    444
fives    555
sixs     666
dtype: int64

In [34]:
frame2 = pd.concat([series1, series2], keys=["Number1","Number2"])

In [35]:
frame2

Number1  zeros       0
         ones      111
         twos      222
         threes    333
Number2  fours     444
         fives     555
         sixs      666
dtype: int64

In [36]:
frame2.unstack()

         fives  fours   ones   sixs  threes   twos  zeros
Number1    NaN    NaN  111.0    NaN   333.0  222.0    0.0
Number2  555.0  444.0    NaN  666.0     NaN    NaN    NaN