In [8]:
import pandas as pd
import numpy as np

In [6]:
from google.colab import files

uploaded = files.upload()

Saving exercise.csv to exercise (4).csv

In [9]:
df = pd.read_csv("exercise.csv")

In [10]:
df

        User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate Body_Temp
0      14733363    male   68   190.0    94.0        29       105.0      40.8
1      14861698  female   20   166.0    60.0        14        94.0      40.3
2      11179863    male   69   179.0    79.0         5        88.0      38.7
3      16180408  female   34   179.0    71.0        13       100.0      40.5
4      17771927  female   27   154.0    58.0        10        81.0      39.8
...         ...     ...  ...     ...     ...       ...         ...       ...
14995  15644082  female   20   193.0    86.0        11        92.0      40.4
14996  17212577  female   27   165.0    65.0         6        85.0      39.2
14997  17271188  female   43   159.0    58.0        16        90.0      40.1
14998  18643037    male   78   193.0    97.0         2        84.0      38.3
14999  11751526    male   63   173.0    79.0        18        92.0      40.5

[15000 rows x 8 columns]

In [12]:
df.isnull()

       User_ID  Gender    Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0        False   False  False   False   False     False       False      False
1        False   False  False   False   False     False       False      False
2        False   False  False   False   False     False       False      False
3        False   False  False   False   False     False       False      False
4        False   False  False   False   False     False       False      False
...        ...     ...    ...     ...     ...       ...         ...        ...
14995    False   False  False   False   False     False       False      False
14996    False   False  False   False   False     False       False      False
14997    False   False  False   False   False     False       False      False
14998    False   False  False   False   False     False       False      False
14999    False   False  False   False   False     False       False      False

[15000 rows x 8 columns]

In [13]:
df.notnull()

       User_ID  Gender   Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0         True    True  True    True    True      True        True       True
1         True    True  True    True    True      True        True       True
2         True    True  True    True    True      True        True       True
3         True    True  True    True    True      True        True       True
4         True    True  True    True    True      True        True       True
...        ...     ...   ...     ...     ...       ...         ...        ...
14995     True    True  True    True    True      True        True       True
14996     True    True  True    True    True      True        True       True
14997     True    True  True    True    True      True        True       True
14998     True    True  True    True    True      True        True       True
14999     True    True  True    True    True      True        True       True

[15000 rows x 8 columns]

In [14]:
df.isnull().sum()

User_ID       0
Gender        1
Age           0
Height        1
Weight        1
Duration      0
Heart_Rate    1
Body_Temp     0
dtype: int64

In [15]:
df.isnull().sum().sum()

np.int64(4)

In [16]:
df.count()

User_ID       15000
Gender        14999
Age           15000
Height        14999
Weight        14999
Duration      15000
Heart_Rate    14999
Body_Temp     15000
dtype: int64

In [17]:
df[df.isnull().any(axis=1)]

      User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate Body_Temp
96   14342169  female   57   171.0    74.0         2         NaN      38.6
178  12845462    male   36   202.0     NaN         6        87.0      39.1
253  18548803     NaN   50   157.0    60.0         6        91.0      39.4
318  13586767  female   37     NaN    61.0        25       103.0      40.7

In [18]:
(df.isnull().sum()/len(df))*100

User_ID       0.000000
Gender        0.006667
Age           0.000000
Height        0.006667
Weight        0.006667
Duration      0.000000
Heart_Rate    0.006667
Body_Temp     0.000000
dtype: float64

In [19]:
df.dropna()

        User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate Body_Temp
0      14733363    male   68   190.0    94.0        29       105.0      40.8
1      14861698  female   20   166.0    60.0        14        94.0      40.3
2      11179863    male   69   179.0    79.0         5        88.0      38.7
3      16180408  female   34   179.0    71.0        13       100.0      40.5
4      17771927  female   27   154.0    58.0        10        81.0      39.8
...         ...     ...  ...     ...     ...       ...         ...       ...
14995  15644082  female   20   193.0    86.0        11        92.0      40.4
14996  17212577  female   27   165.0    65.0         6        85.0      39.2
14997  17271188  female   43   159.0    58.0        16        90.0      40.1
14998  18643037    male   78   193.0    97.0         2        84.0      38.3
14999  11751526    male   63   173.0    79.0        18        92.0      40.5

[14996 rows x 8 columns]

In [20]:
df.dropna(how='all')

        User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate Body_Temp
0      14733363    male   68   190.0    94.0        29       105.0      40.8
1      14861698  female   20   166.0    60.0        14        94.0      40.3
2      11179863    male   69   179.0    79.0         5        88.0      38.7
3      16180408  female   34   179.0    71.0        13       100.0      40.5
4      17771927  female   27   154.0    58.0        10        81.0      39.8
...         ...     ...  ...     ...     ...       ...         ...       ...
14995  15644082  female   20   193.0    86.0        11        92.0      40.4
14996  17212577  female   27   165.0    65.0         6        85.0      39.2
14997  17271188  female   43   159.0    58.0        16        90.0      40.1
14998  18643037    male   78   193.0    97.0         2        84.0      38.3
14999  11751526    male   63   173.0    79.0        18        92.0      40.5

[15000 rows x 8 columns]

In [21]:
df.dropna(axis=1)

        User_ID  Age  Duration Body_Temp
0      14733363   68        29      40.8
1      14861698   20        14      40.3
2      11179863   69         5      38.7
3      16180408   34        13      40.5
4      17771927   27        10      39.8
...         ...  ...       ...       ...
14995  15644082   20        11      40.4
14996  17212577   27         6      39.2
14997  17271188   43        16      40.1
14998  18643037   78         2      38.3
14999  11751526   63        18      40.5

[15000 rows x 4 columns]

In [22]:
df.dropna(how='all', axis=1)

        User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate Body_Temp
0      14733363    male   68   190.0    94.0        29       105.0      40.8
1      14861698  female   20   166.0    60.0        14        94.0      40.3
2      11179863    male   69   179.0    79.0         5        88.0      38.7
3      16180408  female   34   179.0    71.0        13       100.0      40.5
4      17771927  female   27   154.0    58.0        10        81.0      39.8
...         ...     ...  ...     ...     ...       ...         ...       ...
14995  15644082  female   20   193.0    86.0        11        92.0      40.4
14996  17212577  female   27   165.0    65.0         6        85.0      39.2
14997  17271188  female   43   159.0    58.0        16        90.0      40.1
14998  18643037    male   78   193.0    97.0         2        84.0      38.3
14999  11751526    male   63   173.0    79.0        18        92.0      40.5

[15000 rows x 8 columns]

In [23]:
df.dropna(thresh=5)

        User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate Body_Temp
0      14733363    male   68   190.0    94.0        29       105.0      40.8
1      14861698  female   20   166.0    60.0        14        94.0      40.3
2      11179863    male   69   179.0    79.0         5        88.0      38.7
3      16180408  female   34   179.0    71.0        13       100.0      40.5
4      17771927  female   27   154.0    58.0        10        81.0      39.8
...         ...     ...  ...     ...     ...       ...         ...       ...
14995  15644082  female   20   193.0    86.0        11        92.0      40.4
14996  17212577  female   27   165.0    65.0         6        85.0      39.2
14997  17271188  female   43   159.0    58.0        16        90.0      40.1
14998  18643037    male   78   193.0    97.0         2        84.0      38.3
14999  11751526    male   63   173.0    79.0        18        92.0      40.5

[15000 rows x 8 columns]

In [24]:
df.fillna(0)

        User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate Body_Temp
0      14733363    male   68   190.0    94.0        29       105.0      40.8
1      14861698  female   20   166.0    60.0        14        94.0      40.3
2      11179863    male   69   179.0    79.0         5        88.0      38.7
3      16180408  female   34   179.0    71.0        13       100.0      40.5
4      17771927  female   27   154.0    58.0        10        81.0      39.8
...         ...     ...  ...     ...     ...       ...         ...       ...
14995  15644082  female   20   193.0    86.0        11        92.0      40.4
14996  17212577  female   27   165.0    65.0         6        85.0      39.2
14997  17271188  female   43   159.0    58.0        16        90.0      40.1
14998  18643037    male   78   193.0    97.0         2        84.0      38.3
14999  11751526    male   63   173.0    79.0        18        92.0      40.5

[15000 rows x 8 columns]

In [25]:
df.fillna(100)

        User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate Body_Temp
0      14733363    male   68   190.0    94.0        29       105.0      40.8
1      14861698  female   20   166.0    60.0        14        94.0      40.3
2      11179863    male   69   179.0    79.0         5        88.0      38.7
3      16180408  female   34   179.0    71.0        13       100.0      40.5
4      17771927  female   27   154.0    58.0        10        81.0      39.8
...         ...     ...  ...     ...     ...       ...         ...       ...
14995  15644082  female   20   193.0    86.0        11        92.0      40.4
14996  17212577  female   27   165.0    65.0         6        85.0      39.2
14997  17271188  female   43   159.0    58.0        16        90.0      40.1
14998  18643037    male   78   193.0    97.0         2        84.0      38.3
14999  11751526    male   63   173.0    79.0        18        92.0      40.5

[15000 rows x 8 columns]

In [26]:
df.fillna(df.mean(numeric_only=True))

        User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate Body_Temp
0      14733363    male   68   190.0    94.0        29       105.0      40.8
1      14861698  female   20   166.0    60.0        14        94.0      40.3
2      11179863    male   69   179.0    79.0         5        88.0      38.7
3      16180408  female   34   179.0    71.0        13       100.0      40.5
4      17771927  female   27   154.0    58.0        10        81.0      39.8
...         ...     ...  ...     ...     ...       ...         ...       ...
14995  15644082  female   20   193.0    86.0        11        92.0      40.4
14996  17212577  female   27   165.0    65.0         6        85.0      39.2
14997  17271188  female   43   159.0    58.0        16        90.0      40.1
14998  18643037    male   78   193.0    97.0         2        84.0      38.3
14999  11751526    male   63   173.0    79.0        18        92.0      40.5

[15000 rows x 8 columns]

In [27]:
df.fillna(df.median(numeric_only=True))

        User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate Body_Temp
0      14733363    male   68   190.0    94.0        29       105.0      40.8
1      14861698  female   20   166.0    60.0        14        94.0      40.3
2      11179863    male   69   179.0    79.0         5        88.0      38.7
3      16180408  female   34   179.0    71.0        13       100.0      40.5
4      17771927  female   27   154.0    58.0        10        81.0      39.8
...         ...     ...  ...     ...     ...       ...         ...       ...
14995  15644082  female   20   193.0    86.0        11        92.0      40.4
14996  17212577  female   27   165.0    65.0         6        85.0      39.2
14997  17271188  female   43   159.0    58.0        16        90.0      40.1
14998  18643037    male   78   193.0    97.0         2        84.0      38.3
14999  11751526    male   63   173.0    79.0        18        92.0      40.5

[15000 rows x 8 columns]

In [28]:
df.fillna(df.mode().iloc[0])

        User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate Body_Temp
0      14733363    male   68   190.0    94.0        29       105.0      40.8
1      14861698  female   20   166.0    60.0        14        94.0      40.3
2      11179863    male   69   179.0    79.0         5        88.0      38.7
3      16180408  female   34   179.0    71.0        13       100.0      40.5
4      17771927  female   27   154.0    58.0        10        81.0      39.8
...         ...     ...  ...     ...     ...       ...         ...       ...
14995  15644082  female   20   193.0    86.0        11        92.0      40.4
14996  17212577  female   27   165.0    65.0         6        85.0      39.2
14997  17271188  female   43   159.0    58.0        16        90.0      40.1
14998  18643037    male   78   193.0    97.0         2        84.0      38.3
14999  11751526    male   63   173.0    79.0        18        92.0      40.5

[15000 rows x 8 columns]

In [29]:
df.ffill()

        User_ID  Gender  Age  Height  Weight  Duration  Heart_Rate Body_Temp
0      14733363    male   68   190.0    94.0        29       105.0      40.8
1      14861698  female   20   166.0    60.0        14        94.0      40.3
2      11179863    male   69   179.0    79.0         5        88.0      38.7
3      16180408  female   34   179.0    71.0        13       100.0      40.5
4      17771927  female   27   154.0    58.0        10        81.0      39.8
...         ...     ...  ...     ...     ...       ...         ...       ...
14995  15644082  female   20   193.0    86.0        11        92.0      40.4
14996  17212577  female   27   165.0    65.0         6        85.0      39.2
14997  17271188  female   43   159.0    58.0        16        90.0      40.1
14998  18643037    male   78   193.0    97.0         2        84.0      38.3
14999  11751526    male   63   173.0    79.0        18        92.0      40.5

[15000 rows x 8 columns]

In [30]:
df.mean(numeric_only=True)

User_ID       1.497736e+07
Age           4.278980e+01
Height        1.744657e+02
Weight        7.496460e+01
Duration      1.553060e+01
Heart_Rate    9.552003e+01
dtype: float64