In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Caravan.csv to Caravan.csv

In [ ]:
df = pd.read_csv("Caravan.csv")
df

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
0,1,33,1,3,2,8,0,5,1,3,...,0,0,0,1,0,0,0,0,0,No
1,2,37,1,2,2,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
2,3,37,1,2,2,8,0,4,2,4,...,0,0,0,1,0,0,0,0,0,No
3,4,9,1,3,3,3,2,3,2,4,...,0,0,0,1,0,0,0,0,0,No
4,5,40,1,4,2,10,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5817,5818,36,1,1,2,8,0,6,1,2,...,0,0,0,1,0,0,0,0,0,No
5818,5819,35,1,4,4,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
5819,5820,33,1,3,4,8,0,6,0,3,...,0,0,0,1,0,0,0,0,0,Yes
5820,5821,34,1,3,2,8,0,7,0,2,...,0,0,0,0,0,0,0,0,0,No
5821,5822,33,1,3,3,8,0,6,1,2,...,0,0,0,0,0,0,0,0,0,No

In [ ]:
df.isnull()

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5817,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5818,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5819,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5820,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5821,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.dropna(thresh=5, axis=1)

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
0,1,33,1,3,2,8,0,5,1,3,...,0,0,0,1,0,0,0,0,0,No
1,2,37,1,2,2,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
2,3,37,1,2,2,8,0,4,2,4,...,0,0,0,1,0,0,0,0,0,No
3,4,9,1,3,3,3,2,3,2,4,...,0,0,0,1,0,0,0,0,0,No
4,5,40,1,4,2,10,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5817,5818,36,1,1,2,8,0,6,1,2,...,0,0,0,1,0,0,0,0,0,No
5818,5819,35,1,4,4,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
5819,5820,33,1,3,4,8,0,6,0,3,...,0,0,0,1,0,0,0,0,0,Yes
5820,5821,34,1,3,2,8,0,7,0,2,...,0,0,0,0,0,0,0,0,0,No
5821,5822,33,1,3,3,8,0,6,1,2,...,0,0,0,0,0,0,0,0,0,No

In [ ]:
df.mean(numeric_only=True)

rownames    2911.500000
MOSTYPE       24.253349
MAANTHUI       1.110615
MGEMOMV        2.678805
MGEMLEEF       2.991240
               ...
AZEILPL        0.000515
APLEZIER       0.006012
AFIETS         0.031776
AINBOED        0.007901
ABYSTAND       0.014256
Length: 86, dtype: float64

In [ ]:
df.sum(numeric_only=True)

rownames    16950753
MOSTYPE       141203
MAANTHUI        6466
MGEMOMV        15596
MGEMLEEF       17415
              ...
AZEILPL            3
APLEZIER          35
AFIETS           185
AINBOED           46
ABYSTAND          83
Length: 86, dtype: int64

In [ ]:
filled_df = df.fillna(0)

filled_df

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
0,1,33,1,3,2,8,0,5,1,3,...,0,0,0,1,0,0,0,0,0,No
1,2,37,1,2,2,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
2,3,37,1,2,2,8,0,4,2,4,...,0,0,0,1,0,0,0,0,0,No
3,4,9,1,3,3,3,2,3,2,4,...,0,0,0,1,0,0,0,0,0,No
4,5,40,1,4,2,10,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5817,5818,36,1,1,2,8,0,6,1,2,...,0,0,0,1,0,0,0,0,0,No
5818,5819,35,1,4,4,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
5819,5820,33,1,3,4,8,0,6,0,3,...,0,0,0,1,0,0,0,0,0,Yes
5820,5821,34,1,3,2,8,0,7,0,2,...,0,0,0,0,0,0,0,0,0,No
5821,5822,33,1,3,3,8,0,6,1,2,...,0,0,0,0,0,0,0,0,0,No

In [ ]:
df.mean(numeric_only=True)

rownames    2911.500000
MOSTYPE       24.253349
MAANTHUI       1.110615
MGEMOMV        2.678805
MGEMLEEF       2.991240
               ...
AZEILPL        0.000515
APLEZIER       0.006012
AFIETS         0.031776
AINBOED        0.007901
ABYSTAND       0.014256
Length: 86, dtype: float64

In [ ]:
df.mean(numeric_only=True)

rownames    2911.500000
MOSTYPE       24.253349
MAANTHUI       1.110615
MGEMOMV        2.678805
MGEMLEEF       2.991240
               ...
AZEILPL        0.000515
APLEZIER       0.006012
AFIETS         0.031776
AINBOED        0.007901
ABYSTAND       0.014256
Length: 86, dtype: float64

In [ ]:
df.ffill()

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
0,1,33,1,3,2,8,0,5,1,3,...,0,0,0,1,0,0,0,0,0,No
1,2,37,1,2,2,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
2,3,37,1,2,2,8,0,4,2,4,...,0,0,0,1,0,0,0,0,0,No
3,4,9,1,3,3,3,2,3,2,4,...,0,0,0,1,0,0,0,0,0,No
4,5,40,1,4,2,10,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5817,5818,36,1,1,2,8,0,6,1,2,...,0,0,0,1,0,0,0,0,0,No
5818,5819,35,1,4,4,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
5819,5820,33,1,3,4,8,0,6,0,3,...,0,0,0,1,0,0,0,0,0,Yes
5820,5821,34,1,3,2,8,0,7,0,2,...,0,0,0,0,0,0,0,0,0,No
5821,5822,33,1,3,3,8,0,6,1,2,...,0,0,0,0,0,0,0,0,0,No

In [ ]:
df.bfill()

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,APERSONG,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase
0,1,33,1,3,2,8,0,5,1,3,...,0,0,0,1,0,0,0,0,0,No
1,2,37,1,2,2,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
2,3,37,1,2,2,8,0,4,2,4,...,0,0,0,1,0,0,0,0,0,No
3,4,9,1,3,3,3,2,3,2,4,...,0,0,0,1,0,0,0,0,0,No
4,5,40,1,4,2,10,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5817,5818,36,1,1,2,8,0,6,1,2,...,0,0,0,1,0,0,0,0,0,No
5818,5819,35,1,4,4,8,1,4,1,4,...,0,0,0,1,0,0,0,0,0,No
5819,5820,33,1,3,4,8,0,6,0,3,...,0,0,0,1,0,0,0,0,0,Yes
5820,5821,34,1,3,2,8,0,7,0,2,...,0,0,0,0,0,0,0,0,0,No
5821,5822,33,1,3,3,8,0,6,1,2,...,0,0,0,0,0,0,0,0,0,No

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [ ]:
median_imputer = SimpleImputer(strategy="median")

df["MOSTYPE"] = median_imputer.fit_transform(df[["MOSTYPE"]])
df

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase,OSTYPE
0,1,33.0,1,3,2,8,0,5,1,3,...,0,0,1,0,0,0,0,0,No,33.0
1,2,37.0,1,2,2,8,1,4,1,4,...,0,0,1,0,0,0,0,0,No,37.0
2,3,37.0,1,2,2,8,0,4,2,4,...,0,0,1,0,0,0,0,0,No,37.0
3,4,9.0,1,3,3,3,2,3,2,4,...,0,0,1,0,0,0,0,0,No,9.0
4,5,40.0,1,4,2,10,1,4,1,4,...,0,0,1,0,0,0,0,0,No,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5817,5818,36.0,1,1,2,8,0,6,1,2,...,0,0,1,0,0,0,0,0,No,36.0
5818,5819,35.0,1,4,4,8,1,4,1,4,...,0,0,1,0,0,0,0,0,No,35.0
5819,5820,33.0,1,3,4,8,0,6,0,3,...,0,0,1,0,0,0,0,0,Yes,33.0
5820,5821,34.0,1,3,2,8,0,7,0,2,...,0,0,0,0,0,0,0,0,No,34.0
5821,5822,33.0,1,3,3,8,0,6,1,2,...,0,0,0,0,0,0,0,0,No,33.0

In [ ]:
median_imputer = SimpleImputer(strategy="median")

df["MOSTYPE"] = median_imputer.fit_transform(df[["MOSTYPE"]])
df

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase,OSTYPE
0,1,33.0,1,3,2,8,0,5,1,3,...,0,0,1,0,0,0,0,0,No,33.0
1,2,37.0,1,2,2,8,1,4,1,4,...,0,0,1,0,0,0,0,0,No,37.0
2,3,37.0,1,2,2,8,0,4,2,4,...,0,0,1,0,0,0,0,0,No,37.0
3,4,9.0,1,3,3,3,2,3,2,4,...,0,0,1,0,0,0,0,0,No,9.0
4,5,40.0,1,4,2,10,1,4,1,4,...,0,0,1,0,0,0,0,0,No,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5817,5818,36.0,1,1,2,8,0,6,1,2,...,0,0,1,0,0,0,0,0,No,36.0
5818,5819,35.0,1,4,4,8,1,4,1,4,...,0,0,1,0,0,0,0,0,No,35.0
5819,5820,33.0,1,3,4,8,0,6,0,3,...,0,0,1,0,0,0,0,0,Yes,33.0
5820,5821,34.0,1,3,2,8,0,7,0,2,...,0,0,0,0,0,0,0,0,No,34.0
5821,5822,33.0,1,3,3,8,0,6,1,2,...,0,0,0,0,0,0,0,0,No,33.0

In [ ]:
mode_imputer = SimpleImputer(strategy="most_frequent")

df["MOSTYPE"] = mode_imputer.fit_transform(df[["MOSTYPE"]])
df

,rownames,MOSTYPE,MAANTHUI,MGEMOMV,MGEMLEEF,MOSHOOFD,MGODRK,MGODPR,MGODOV,MGODGE,...,AGEZONG,AWAOREG,ABRAND,AZEILPL,APLEZIER,AFIETS,AINBOED,ABYSTAND,Purchase,OSTYPE
0,1,33.0,1,3,2,8,0,5,1,3,...,0,0,1,0,0,0,0,0,No,33.0
1,2,37.0,1,2,2,8,1,4,1,4,...,0,0,1,0,0,0,0,0,No,37.0
2,3,37.0,1,2,2,8,0,4,2,4,...,0,0,1,0,0,0,0,0,No,37.0
3,4,9.0,1,3,3,3,2,3,2,4,...,0,0,1,0,0,0,0,0,No,9.0
4,5,40.0,1,4,2,10,1,4,1,4,...,0,0,1,0,0,0,0,0,No,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5817,5818,36.0,1,1,2,8,0,6,1,2,...,0,0,1,0,0,0,0,0,No,36.0
5818,5819,35.0,1,4,4,8,1,4,1,4,...,0,0,1,0,0,0,0,0,No,35.0
5819,5820,33.0,1,3,4,8,0,6,0,3,...,0,0,1,0,0,0,0,0,Yes,33.0
5820,5821,34.0,1,3,2,8,0,7,0,2,...,0,0,0,0,0,0,0,0,No,34.0
5821,5822,33.0,1,3,3,8,0,6,1,2,...,0,0,0,0,0,0,0,0,No,33.0