In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler

In [ ]:
marks = [34, 45, 56, 67, 72, 88, 91, 39, 64, 77, 81, 95, 52, 47]

In [ ]:
bins = [0,40,60,80,100]

categories = pd.cut(marks,bins)

categories

[(0, 40], (40, 60], (40, 60], (60, 80], (60, 80], ..., (60, 80], (80, 100], (80, 100], (40, 60], (40, 60]]
Length: 14
Categories (4, interval[int64, right]): [(0, 40] < (40, 60] < (60, 80] < (80, 100]]

In [ ]:
pd.Series(categories).value_counts()

(40, 60]     4
(60, 80]     4
(80, 100]    4
(0, 40]      2
Name: count, dtype: int64

In [ ]:
labels=["Fail","Average","Good","Excellent"]

pd.cut(marks,bins,labels=labels)

['Fail', 'Average', 'Average', 'Good', 'Good', ..., 'Good', 'Excellent', 'Excellent', 'Average', 'Average']
Length: 14
Categories (4, object): ['Fail' < 'Average' < 'Good' < 'Excellent']

In [ ]:
random_numbers=np.random.randint(10,100,50)

random_numbers

array([66, 25, 72, 64, 42, 43, 34, 43, 10, 15, 96, 94, 10, 34, 69, 57, 32,
       35, 55, 50, 93, 44, 25, 58, 56, 63, 14, 11, 90, 71, 38, 98, 39, 38,
       31, 99, 89, 38, 45, 49, 89, 21, 55, 82, 80, 19, 92, 21, 22, 59])

In [ ]:
pd.cut(random_numbers,5)

[(63.4, 81.2], (9.911, 27.8], (63.4, 81.2], (63.4, 81.2], (27.8, 45.6], ..., (9.911, 27.8], (81.2, 99.0], (9.911, 27.8], (9.911, 27.8], (45.6, 63.4]]
Length: 50
Categories (5, interval[float64, right]): [(9.911, 27.8] < (27.8, 45.6] < (45.6, 63.4] <
                                           (63.4, 81.2] < (81.2, 99.0]]

In [ ]:
pd.qcut(random_numbers,5)

[(56.4, 80.4], (9.999, 25.0], (56.4, 80.4], (56.4, 80.4], (40.8, 56.4], ..., (9.999, 25.0], (80.4, 99.0], (9.999, 25.0], (9.999, 25.0], (56.4, 80.4]]
Length: 50
Categories (5, interval[float64, right]): [(9.999, 25.0] < (25.0, 40.8] < (40.8, 56.4] <
                                           (56.4, 80.4] < (80.4, 99.0]]

In [ ]:
pd.Series(pd.qcut(random_numbers,5)).value_counts()

(9.999, 25.0]    11
(40.8, 56.4]     10
(56.4, 80.4]     10
(80.4, 99.0]     10
(25.0, 40.8]      9
Name: count, dtype: int64

In [3]:
from google.colab import files

uploaded = files.upload()

Saving fraudTrainsmall-part-001.csv to fraudTrainsmall-part-001.csv

In [4]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [5]:
df = pd.read_csv("fraudTrainsmall-part-001.csv")

In [6]:
df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [7]:
df.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             1000 non-null   int64
 1   trans_date_trans_time  1000 non-null   object
 2   cc_num                 1000 non-null   int64
 3   merchant               1000 non-null   object
 4   category               1000 non-null   object
 5   amt                    1000 non-null   float64
 6   first                  1000 non-null   object
 7   last                   1000 non-null   object
 8   gender                 1000 non-null   object
 9   street                 1000 non-null   object
 10  city                   1000 non-null   object
 11  state                  1000 non-null   object
 12  zip                    1000 non-null   int64
 13  lat                    1000 non-null   float64
 14  long                   1000 non-null   float64
 15  city_pop               1000 non-null   int64
 16  job                    1000 non-null   object
 17  dob                    1000 non-null   object
 18  trans_num              1000 non-null   object
 19  unix_time              1000 non-null   int64
 20  merch_lat              1000 non-null   float64
 21  merch_long             1000 non-null   float64
 22  is_fraud               1000 non-null   int64
dtypes: float64(5), int64(6), object(12)
memory usage: 179.8+ KB

In [9]:
df.describe()

,Unnamed: 0,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
count,1000.000000,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,1.000000e+03,1000.000000,1000.000000,1000.0
mean,499.500000,4.166033e+17,78.348710,49209.013000,38.635484,-90.577526,7.965088e+04,1.325399e+09,38.639228,-90.566698,0.0
std,288.819436,1.304201e+18,113.088651,27065.627192,4.930545,14.333060,2.525475e+05,1.331330e+04,4.965199,14.349162,0.0
min,0.000000,6.042310e+10,1.030000,1330.000000,20.027100,-165.672300,2.300000e+01,1.325376e+09,19.209212,-166.148374,0.0
25%,249.750000,1.800365e+14,19.865000,25091.750000,35.526275,-98.029875,6.800000e+02,1.325387e+09,35.505187,-97.723953,0.0
50%,499.500000,3.514866e+15,58.970000,48404.500000,39.523600,-87.764400,2.328000e+03,1.325400e+09,39.362646,-87.541585,0.0
75%,749.250000,4.658491e+15,93.187500,72018.750000,41.701225,-80.057300,1.905400e+04,1.325411e+09,41.854788,-80.021328,0.0
max,999.000000,4.992346e+18,1636.870000,99783.000000,64.755600,-67.950300,2.906700e+06,1.325422e+09,65.336985,-67.938911,0.0

In [10]:
df.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [13]:
bins = [0, 20, 50, 100, 500, 1000, 5000]

labels = [
    "Very Low",
    "Low",
    "Medium",
    "High",
    "Very High",
    "Premium"
]

df["Amount_Category"] = pd.cut(df["amt"],
                               bins=bins,
                               labels=labels)

In [14]:
df[["amt","Amount_Category"]].head(20)

       amt Amount_Category
0     4.97        Very Low
1   107.23            High
2   220.11            High
3    45.00             Low
4    41.96             Low
5    94.63          Medium
6    44.54             Low
7    71.65          Medium
8     4.27        Very Low
9   198.39            High
10   24.74             Low
11    7.77        Very Low
12   71.22          Medium
13   96.29          Medium
14    7.77        Very Low
15    3.26        Very Low
16  327.00            High
17  341.67            High
18   63.07          Medium
19   44.71             Low

In [15]:
df["Amount_Category"].value_counts()

Amount_Category
Medium       376
Very Low     252
High         211
Low          150
Very High      7
Premium        4
Name: count, dtype: int64

In [16]:
pd.cut(df["amt"],5)

0      (-0.606, 328.198]
1      (-0.606, 328.198]
2      (-0.606, 328.198]
3      (-0.606, 328.198]
4      (-0.606, 328.198]
             ...
995    (-0.606, 328.198]
996    (-0.606, 328.198]
997    (-0.606, 328.198]
998    (-0.606, 328.198]
999    (-0.606, 328.198]
Name: amt, Length: 1000, dtype: category
Categories (5, interval[float64, right]): [(-0.606, 328.198] < (328.198, 655.366] <
                                           (655.366, 982.534] < (982.534, 1309.702] <
                                           (1309.702, 1636.87]]

In [17]:
df["Amount_QCut"] = pd.qcut(df["amt"],4)

In [18]:
df["Amount_QCut"].value_counts()

Amount_QCut
(1.0290000000000001, 19.865]    250
(19.865, 58.97]                 250
(58.97, 93.188]                 250
(93.188, 1636.87]               250
Name: count, dtype: int64

In [19]:
df[["amt","Amount_QCut"]].head(20)

       amt                   Amount_QCut
0     4.97  (1.0290000000000001, 19.865]
1   107.23             (93.188, 1636.87]
2   220.11             (93.188, 1636.87]
3    45.00               (19.865, 58.97]
4    41.96               (19.865, 58.97]
5    94.63             (93.188, 1636.87]
6    44.54               (19.865, 58.97]
7    71.65               (58.97, 93.188]
8     4.27  (1.0290000000000001, 19.865]
9   198.39             (93.188, 1636.87]
10   24.74               (19.865, 58.97]
11    7.77  (1.0290000000000001, 19.865]
12   71.22               (58.97, 93.188]
13   96.29             (93.188, 1636.87]
14    7.77  (1.0290000000000001, 19.865]
15    3.26  (1.0290000000000001, 19.865]
16  327.00             (93.188, 1636.87]
17  341.67             (93.188, 1636.87]
18   63.07               (58.97, 93.188]
19   44.71               (19.865, 58.97]

In [20]:
df[df["amt"] > 1000]

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,Amount_Category,Amount_QCut
232,232,2019-01-01 02:54:10,4311368326621416041,fraud_Kassulke PLC,shopping_net,1055.47,Phillip,Delacruz,M,26678 Lisa Locks Apt. 904,...,648,Community arts worker,1969-09-21,adca67d0a40b26fb8afeccbae31b7828,1325386450,39.940564,-103.528231,0,Premium,"(93.188, 1636.87]"
511,511,2019-01-01 06:43:54,4509142395811241,fraud_McGlynn-Heathcote,misc_net,1636.87,Margaret,Williams,F,165 Jerry Meadows Suite 460,...,1324,"Engineer, technical sales",1926-07-12,9b13fb1ce565b55afe4106ecdee9346b,1325400234,31.608415,-83.145823,0,Premium,"(93.188, 1636.87]"
723,723,2019-01-01 09:23:55,4265776278887457,"fraud_Rippin, Kub and Mann",misc_net,1047.52,Christine,Best,F,68248 Deanna Land,...,969,"Physicist, medical",1954-01-05,bb5654f0f82ace48aa6e4f45db7c64c5,1325409835,34.887449,-92.623326,0,Premium,"(93.188, 1636.87]"
824,824,2019-01-01 10:29:29,630469040731,fraud_Auer-West,shopping_net,1433.54,Meredith,Ayala,F,7107 Henderson Station,...,1288,Barrister,1936-05-01,cdf73aea45a42592972ad9668315b8c2,1325413769,45.873314,-121.589038,0,Premium,"(93.188, 1636.87]"

In [21]:
len(df[df["amt"] > 1000])

4

In [23]:
df["amt"].max()

1636.87

In [24]:
df["amt"].min()

1.03

In [25]:
df["amt"].mean()

np.float64(78.34871)

In [26]:
scaler = MinMaxScaler()

df["Amount_MinMax"] = scaler.fit_transform(df[["amt"]])

df[["amt","Amount_MinMax"]].head(10)

      amt  Amount_MinMax
0    4.97       0.002409
1  107.23       0.064921
2  220.11       0.133925
3   45.00       0.026879
4   41.96       0.025021
5   94.63       0.057218
6   44.54       0.026598
7   71.65       0.043170
8    4.27       0.001981
9  198.39       0.120647

In [27]:
scaler = StandardScaler()

df["Amount_Standard"] = scaler.fit_transform(df[["amt"]])

df[["amt","Amount_Standard"]].head(10)

      amt  Amount_Standard
0    4.97        -0.649185
1  107.23         0.255514
2  220.11         1.254169
3   45.00        -0.295038
4   41.96        -0.321933
5   94.63         0.144041
6   44.54        -0.299107
7   71.65        -0.059264
8    4.27        -0.655378
9  198.39         1.062011

In [28]:
df[["amt","Amount_MinMax","Amount_Standard"]].head(20)

       amt  Amount_MinMax  Amount_Standard
0     4.97       0.002409        -0.649185
1   107.23       0.064921         0.255514
2   220.11       0.133925         1.254169
3    45.00       0.026879        -0.295038
4    41.96       0.025021        -0.321933
5    94.63       0.057218         0.144041
6    44.54       0.026598        -0.299107
7    71.65       0.043170        -0.059264
8     4.27       0.001981        -0.655378
9   198.39       0.120647         1.062011
10   24.74       0.014494        -0.474279
11    7.77       0.004120        -0.624413
12   71.22       0.042908        -0.063068
13   96.29       0.058233         0.158727
14    7.77       0.004120        -0.624413
15    3.26       0.001363        -0.664313
16  327.00       0.199268         2.199829
17  341.67       0.208236         2.329615
18   63.07       0.037925        -0.135171
19   44.71       0.026702        -0.297603

In [29]:
df.sort_values("amt",ascending=False).head(10)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,Amount_Category,Amount_QCut,Amount_MinMax,Amount_Standard
511,511,2019-01-01 06:43:54,4509142395811241,fraud_McGlynn-Heathcote,misc_net,1636.87,Margaret,Williams,F,165 Jerry Meadows Suite 460,...,1926-07-12,9b13fb1ce565b55afe4106ecdee9346b,1325400234,31.608415,-83.145823,0,Premium,"(93.188, 1636.87]",1.000000,13.788308
824,824,2019-01-01 10:29:29,630469040731,fraud_Auer-West,shopping_net,1433.54,Meredith,Ayala,F,7107 Henderson Station,...,1936-05-01,cdf73aea45a42592972ad9668315b8c2,1325413769,45.873314,-121.589038,0,Premium,"(93.188, 1636.87]",0.875703,11.989438
232,232,2019-01-01 02:54:10,4311368326621416041,fraud_Kassulke PLC,shopping_net,1055.47,Phillip,Delacruz,M,26678 Lisa Locks Apt. 904,...,1969-09-21,adca67d0a40b26fb8afeccbae31b7828,1325386450,39.940564,-103.528231,0,Premium,"(93.188, 1636.87]",0.644586,8.644636
723,723,2019-01-01 09:23:55,4265776278887457,"fraud_Rippin, Kub and Mann",misc_net,1047.52,Christine,Best,F,68248 Deanna Land,...,1954-01-05,bb5654f0f82ace48aa6e4f45db7c64c5,1325409835,34.887449,-92.623326,0,Premium,"(93.188, 1636.87]",0.639726,8.574302
296,296,2019-01-01 03:51:28,571844099986,fraud_Heathcote LLC,shopping_net,909.66,Susan,Mills,F,005 Cody Estates,...,1952-04-02,ecea96ae40920997dd56b4e0b408d623,1325389888,39.081318,-86.301580,0,Very High,"(93.188, 1636.87]",0.555452,7.354648
770,770,2019-01-01 09:53:44,38580485618059,fraud_Mohr-Bayer,shopping_net,767.18,Teresa,Clark,F,1323 Derek Mission,...,1968-05-13,870bcb4a789f5afcbf32fbe3f49abe89,1325411624,49.342568,-103.496454,0,Very High,"(93.188, 1636.87]",0.468353,6.094121
764,764,2019-01-01 09:51:52,5501083170975659,fraud_Metz-Boehm,shopping_pos,658.55,Wayne,Payne,M,587 Bradley Inlet Suite 281,...,1966-01-04,18aabe3c70bcb95b9784198042b824ac,1325411512,40.229232,-82.340619,0,Very High,"(93.188, 1636.87]",0.401946,5.133067
138,138,2019-01-01 01:41:22,4060579726528237,"fraud_Baumbach, Hodkiewicz and Walsh",shopping_pos,636.41,Steven,Sanders,M,25955 Amy Via,...,1948-11-14,25240538cb76fe0e9f55c3eb2c5e3bf9,1325382082,39.936995,-94.604311,0,Very High,"(93.188, 1636.87]",0.388412,4.937193
286,286,2019-01-01 03:45:30,5559857416065248,"fraud_Romaguera, Cruickshank and Greenholt",shopping_net,511.09,Jack,Hill,M,5916 Susan Bridge Apt. 939,...,1945-12-21,46397744ae13d2c0843e8fba6f164379,1325389530,42.412743,-121.617857,0,Very High,"(93.188, 1636.87]",0.311803,3.828482
580,580,2019-01-01 07:33:23,30404291151692,fraud_Thiel PLC,misc_pos,508.59,Savannah,Lewis,F,537 Walker Freeway,...,1993-10-25,06c97720f8c9fdf220edcc029877363c,1325403203,43.591414,-78.301217,0,Very High,"(93.188, 1636.87]",0.310275,3.806364

In [30]:
df["is_fraud"].value_counts()

is_fraud
0    1000
Name: count, dtype: int64

In [32]:
df.to_csv("fraudTrain_processed.csv",index=False)